name: prueba1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  firebase_dart: ^1.1.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  mailer: ^6.1.2
  percent_indicator: ^4.2.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  fl_chart: ^0.68.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/imagenes/
  - assets/iconos/
