// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJHHGBrfYtzyzJYZvOpYHU65L6eYIlOqs',
    appId: '1:629904184171:web:875df38a01b10f7391322e',
    messagingSenderId: '629904184171',
    projectId: 'prueba1-3e60c',
    authDomain: 'prueba1-3e60c.firebaseapp.com',
    storageBucket: 'prueba1-3e60c.appspot.com',
    measurementId: 'G-RE8BC40VF2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJHHGBrfYtzyzJYZvOpYHU65L6eYIlOqs',
    appId: '1:629904184171:web:ecfc49ddbe53d5df91322e',
    messagingSenderId: '629904184171',
    projectId: 'prueba1-3e60c',
    authDomain: 'prueba1-3e60c.firebaseapp.com',
    storageBucket: 'prueba1-3e60c.appspot.com',
    measurementId: 'G-P5KS4ZMTVJ',
  );
}
